---
kind: ConfigMap
apiVersion: v1
metadata:
  name: myapp-config
  namespace: myns
  labels:
    app: myapp-config

data:
  db_user: root
  db_host: mydb-svc.myns.svc.cluster.local

---
kind: Secret
apiVersion: v1
metadata:
  name: myapp-secret
  namespace: myns
  labels:
    app: myapp-secret

data:
  db_password: Y2hhbmdlaXQ=

---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: myapp-deploy
  namespace: myns
  labels:
    app: myapp-deploy
    version: v1

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-pod
      version: v1
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: myapp-pod
        version: v1
    spec:
      containers:
      - name: myapp
        image: stackupiss/northwind-app:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        env:
        - name: DB_HOST
          value: mydb-svc.myns.svc.cluster.local
        - name: DB_USER
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: db_user
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: myapp-secret
              key: db_password
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef: 
              fieldPath: status.podIP
        ports:
        - name: myapp-port
          containerPort: 3000

---
#FQDN -> mydb-svc.myns.svc.cluster.local
kind: Service
apiVersion: v1

metadata:
  name: myapp-svc
  namespace: myns
  labels:
    app: myapp

spec:
  type: ClusterIP
  selector: 
    app: myapp-pod
  ports:
  - name: myapp-svc-port
    port: 80
    targetPort: myapp-port