---
kind: ServiceAccount
apiVersion: v1
metadata:
  name:  tiller-sa
  namespace: myns

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-myns-rb
  namespace: myns

subjects:
- kind: ServiceAccount
  name: tiller-sa
  namespace: myns

roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: admin

# limit tiller to namespace myns