---
kind: Secret
apiVersion: v1
metadata:
  name: mywtapp-secret
  namespace: myns
  labels:
    app: mywtapp-secret

data:
  app_id: MmZjMWZlZGIxYzcwYTFhNTUzOTk4MDkwYjVmOTc5MmI=

---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: mywtapp-deploy
  namespace: myns
  labels:
    app: mywtapp-deploy
    version: v1

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywtapp-pod
      version: v1
  template:
    metadata:
      name: mywtapp-pod
      labels: 
        app: mywtapp-pod
        version: v1
    spec:
      containers:
      - name: mywtapp
        image: stackupiss/weather:v1
        imagePullPolicy: Always
        env:
        - name: APP_ID
          valueFrom: 
            secretKeyRef:
              name: mywtapp-secret
              key: app_id
        ports:
        - name: myapp-port
          containerPort: 3000

---
#FQDN -> mydb-svc.myns.svc.cluster.local
kind: Service
apiVersion: v1

metadata:
  name: mywtapp-svc
  namespace: myns
  labels:
    app: mywtapp

spec:
  type: ClusterIP
  selector: 
    app: mywtapp-pod
  ports:
  - name: mywtapp-svc-port
    port: 80
    targetPort: myapp-port